package client;

import java.util.Random;
import javax.swing.JDialog;
import server.klasy.Gra;
import server.klasy.Gracz;

/**
 *
 * @author marekszymanski
 */
public class GuiGra extends javax.swing.JFrame {
    Gra gra;
    Gracz gracz;
    
    public GuiGra(Gra gra, Gracz gracz) {
        this.gra = gra;
        this.gracz = gracz;
        
        initComponents();
        uaktualnijStanGry();
        setLocationRelativeTo(null);
        this.setVisible(true);     
    }
    
    //uaktualnia wyświetlane wartości GUI
    public void uaktualnijStanGry()
    {
        jLbl_NazwaGracza.setText(gracz.getNazwa());
//        System.out.println("TEST "+jLbl_NazwaGracza.getText());
        jLbl_WylosowanaKwota.setText(Integer.toString(gra.getWylosowanaKwotaDoWygrania()));
        jLbl_Haslo.setText(gra.getOdgadywaneElementyHasla());
        jLabel5.setText(gra.getKupioneLitery());
        jLbl_KontoGracza1.setText(Integer.toString(gra.getGracze().get(0).getStanKonta()));
        jLbl_KontoGracza2.setText(Integer.toString(gra.getGracze().get(1).getStanKonta()));
        jLbl_KontoGracza3.setText(Integer.toString(gra.getGracze().get(2).getStanKonta()));
//        repaint();
//        validate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLbl_NazwaGracza = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jBtn_KrecKolem = new javax.swing.JButton();
        jLbl_WylosowanaKwota = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLbl_KontoGracza1 = new javax.swing.JLabel();
        jLbl_KontoGracza2 = new javax.swing.JLabel();
        jLbl_KontoGracza3 = new javax.swing.JLabel();
        jLbl_Haslo = new javax.swing.JLabel();
        jComboBox_Litery = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Hasło:");

        jLbl_NazwaGracza.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLbl_NazwaGracza.setText("Gracz 1");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Nazwa:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("Wykorzystane");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText(" ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jBtn_KrecKolem.setText("Kręć kołem");
        jBtn_KrecKolem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_KrecKolemActionPerformed(evt);
            }
        });

        jLbl_WylosowanaKwota.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLbl_WylosowanaKwota.setText("500");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Gracze:");

        jLabel9.setText("Gracz 1");

        jLabel10.setText("Gracz 2");

        jLabel11.setText("Gracz 3");

        jLbl_KontoGracza1.setText("0");

        jLbl_KontoGracza2.setText("0");

        jLbl_KontoGracza3.setText("0");

        jLbl_Haslo.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLbl_Haslo.setText("____ __ __ __ __ _");

        jComboBox_Litery.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jComboBox_Litery.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "Ą", "B", "C", "Ć", "D", "E", "Ę", "F", "G", "H", "I", "J", "K", "L", "Ł", "M", "N", "Ń", "O", "Ó", "P", "R", "S", "Ś", "T", "U", "W", "Y", "Z", "Ź", "Ż" }));
        jComboBox_Litery.setPreferredSize(new java.awt.Dimension(87, 45));
        jComboBox_Litery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_LiteryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLbl_Haslo, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLbl_NazwaGracza, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_KrecKolem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_WylosowanaKwota, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Litery, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLbl_KontoGracza2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLbl_KontoGracza1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbl_KontoGracza3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_Haslo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLbl_NazwaGracza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLbl_KontoGracza1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLbl_KontoGracza2)))
                    .addComponent(jComboBox_Litery, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_WylosowanaKwota, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLbl_KontoGracza3)))
                        .addGap(74, 74, 74)
                        .addComponent(jBtn_KrecKolem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//wyświetla animację kręcenia kołem i losuje wygraną
    private void jBtn_KrecKolemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_KrecKolemActionPerformed
        new Animacja();
        int temp = new Random().nextInt(10) * 100;
//        gracz.setStanKonta(temp);
        System.out.println(gracz.getStanKonta());
        gra.setWylosowanaKwotaDoWygrania(temp);
        uaktualnijStanGry();        
    }//GEN-LAST:event_jBtn_KrecKolemActionPerformed
//pozwala wybrać literę z alfabetu (sprawdza czy była wybrana, czy jest w haśle itp)
    private void jComboBox_LiteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_LiteryActionPerformed
        System.out.println(jComboBox_Litery.getSelectedItem());
        String haslo = gra.getHaslo();
        String wybranaLitera = (String) jComboBox_Litery.getSelectedItem();
        char wybranyChar = wybranaLitera.charAt(0);
//        System.out.println("char = "+wybranyChar);
        if(haslo.contains((CharSequence) jComboBox_Litery.getSelectedItem())){
            for(int i=0;i<haslo.length();i++){
                if(haslo.charAt(i) == wybranyChar){
                    StringBuilder sb = new StringBuilder(gra.getOdgadywaneElementyHasla());
                    sb.setCharAt(i, wybranyChar);
                    gra.setOdgadywaneElementyHasla(sb.toString());
                   
                    //koniec gry
                    if(gra.getHaslo().equals(gra.getOdgadywaneElementyHasla())){
                        gra.findWinner();
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                KoniecGry dialog = new KoniecGry(new javax.swing.JFrame(), true, gra);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                    @Override
                                    public void windowClosing(java.awt.event.WindowEvent e) {
                                        System.exit(0);
                                    }
                                });
                                dialog.setVisible(true);
                            }
                        });
                        return;
                    }
                    gra.getCzyjaTura().setStanKonta(gra.getCzyjaTura().getStanKonta() + gra.getWylosowanaKwotaDoWygrania());
//                    
//                    if(wybranaLitera.equals("A")){//należy dodać lub EYUIOó
//                        gra.getCzyjaTura().setStanKonta(gra.getCzyjaTura().getStanKonta() + gra.getWylosowanaKwotaDoWygrania());
//                        
//                    }
//                    else{
//                        gra.getCzyjaTura().setStanKonta(gra.getCzyjaTura().getStanKonta() + gra.getWylosowanaKwotaDoWygrania());          
////                        gra.getNextGracz();
//                    }                    
                }
            }          
        }
        else{
            gra.getNextGracz();//litera nie była w haśle, zmień turę
        }
        if(gra.getKupioneLitery().contains(wybranaLitera) == false){
            wybranaLitera +=" ";
            wybranaLitera += gra.getKupioneLitery();
            gra.setKupioneLitery(wybranaLitera);
            uaktualnijStanGry();
        }       
    }//GEN-LAST:event_jComboBox_LiteryActionPerformed
//pole w którym podaję hasło, jeśli tak koniec gry
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        if(jTextField1.getText().toUpperCase().equals(gra.getHaslo()))
        {
            System.out.println("TAK");
            gra.setOdgadywaneElementyHasla(gra.getHaslo());
            gra.getCzyjaTura().setStanKonta(gra.getCzyjaTura().getStanKonta()+gra.getWylosowanaKwotaDoWygrania());
            uaktualnijStanGry();
            //koniec gry
            gra.findWinner();
                       java.awt.EventQueue.invokeLater(new Runnable() {
                           public void run() {
                               KoniecGry dialog = new KoniecGry(new javax.swing.JFrame(), true, gra);
                               dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                   @Override
                                   public void windowClosing(java.awt.event.WindowEvent e) {
                                       System.exit(0);
                                   }
                               });
                               dialog.setVisible(true);
                           }
                       });
        }
        else
            System.out.println("NIE");
            //wiadomość "ZŁĄ ODPOWIEDŹ"
    }//GEN-LAST:event_jTextField1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiGra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiGra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiGra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiGra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GuiGra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_KrecKolem;
    private javax.swing.JComboBox jComboBox_Litery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbl_Haslo;
    private javax.swing.JLabel jLbl_KontoGracza1;
    private javax.swing.JLabel jLbl_KontoGracza2;
    private javax.swing.JLabel jLbl_KontoGracza3;
    private javax.swing.JLabel jLbl_NazwaGracza;
    private javax.swing.JLabel jLbl_WylosowanaKwota;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
